### ISSUE TITLE
question on for loop range

### ISSUE THREAD

**Issue by bbrewington** [derac/Odyssey-Court-Records-to-JSON#5]
What is this line of code intended to do?

https://github.com/derac/Odyssey-Court-Records-to-JSON/blob/b46f2043375270e9608a4bec4b298dafd8d422eb/src/scraper.py#L199

believe it's equivalent to:
```python
for day_offset in range(start=args.start_offset, stop=args.days):
```

which means it's creating a range from `start_offset` to `days`, incrementing by 1.  does that make sense?  so if I wanted to start at 10 days ago (i.e. `start_offset=10`) and grab 2 days of data, (i.e. `days=2`) it wouldn't be valid? (that range(...) value would be None type)

**Comment by derac** [comment]
it's iterating through the number of days ago to start scraping to the number of days total you'd like to scrape, backwards:

next line,
date_string = datetime.strftime(TODAY - timedelta(days=day_offset), "%m/%d/%Y")

you'd want to do start_offset=10, days=12
perhaps a bit clunky, but I was considering the use case of scraping a large amount of data and manually restarting from a particular offset if it is interrupted.
