### ISSUE TITLE
scraper.py: hanging equals signs in f-string expressions

### ISSUE THREAD

**Issue by bbrewington** [derac/Odyssey-Court-Records-to-JSON#6]
here's a couple examples (can find rest by Ctrl+F for "= }")

https://github.com/derac/Odyssey-Court-Records-to-JSON/blob/b46f2043375270e9608a4bec4b298dafd8d422eb/src/scraper.py#L166

https://github.com/derac/Odyssey-Court-Records-to-JSON/blob/b46f2043375270e9608a4bec4b298dafd8d422eb/src/scraper.py#L209

**Comment by derac** [comment]
this is a shorthand syntax to print debug info

**Comment by derac** [comment]
https://docs.python.org/3/reference/lexical_analysis.html#f-strings

**Comment by bbrewington** [comment]
won't it try to evaluate the expression inside the curly braces?  doesn't the stuff inside have to be a valid Python expression?

**Comment by bbrewington** [comment]
COOL.  just learned some new python functionality.  closing
